version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "TenantProductManager&Password1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./init.sql:/tmp/init.sql
      - ./entrypoint.sh:/tmp/entrypoint.sh
    entrypoint:
      - /bin/bash
    command:
      - /tmp/entrypoint.sh

  tenantproductmanagerapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TenantProductManager;User Id=TenantProductManagerUser;Password=TenantProductManager&Password1;MultipleActiveResultSets=true;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    volumes:
      - ./wait-for-it-api.sh:/tmp/wait-for-it-api.sh
    entrypoint: ["/bin/bash","/tmp/wait-for-it-api.sh","dotnet", "TenantProductManager.Api.dll"]
    command:
      - /tmp/wait-for-it-api-write.sh
   
volumes:
  sqlserver-data:
